extends "res://checks/check.gd"
## Native exact boundaries, real Romata descriptor modes, queued approach and
## save/restore of pending identity. Parent runs once after integration.
const Talk := preload("res://world/talk_command.gd")
const Registry := preload("res://world/actor_registry.gd")
const Weapons := preload("res://formats/weapons.gd")
const Pak := preload("res://formats/pak.gd")

func _init() -> void:
	super()
	var install := Sacred.find_install()
	assert(not install.is_empty(), "requires retail install")
	var weapons := Weapons.new(install.path_join("pak/weapon.pak"))
	var talk := Talk.new(weapons)
	var pak := Pak.new(install.path_join("pak/items.pak"))
	var definitions: Array[PackedByteArray] = []
	for i in pak.count():
		definitions.append(pak.blob(i))
	weapons.apply_to(definitions)
	expect(talk.bind_definition(1729, definitions[1729]) == "" and talk.bind_definition(1200, definitions[1200]) == "", "actual normalized equipment could not bind")
	expect(weapons.mode(weapons.row_for_type(1729)) == 1, "installed sword descriptor mode moved")
	expect(weapons.mode(weapons.row_for_type(1200)) == 0, "installed off-hand descriptor mode moved")
	expect(talk.equipped_mode(1729, 1200) == {"ok": true, "mode": 8}, "native two-object mode mapping differs")
	expect(talk.equipped_mode(1200, 1729) == {"ok": true, "mode": 1}, "native category13 exception differs")
	expect(Talk.body_radius(8, 0) == 130 and Talk.body_radius(297, 0) == 80 and Talk.body_radius(297, 1) == 110, "native body radius table differs")
	expect(Talk.raw_distance(Vector2i.ZERO, Vector2i(3, 4)) == 5, "native 3-4-5 distance differs")
	expect(Talk.raw_distance(Vector2i.ZERO, Vector2i(1, 1)) == 1 and Talk.raw_distance(Vector2i.ZERO, Vector2i(2, 2)) == 3, "native nearest-integer square root differs")
	expect(Talk.raw_distance(Vector2i.ZERO, Vector2i(32001, 0)) == 32000, "native coordinate saturation differs")
	var live_center := Vector2(3470.5, 2779.5)
	var expected_raw := Vector2i(int(3470.5 * 53.66563), int(2779.5 * 53.66563))
	expect(Talk.native_position(live_center) == expected_raw, "live actor center received another half-cell creation bias")
	var registry := Registry.new()
	var hero_id := registry.spawn(8, _cell(26), 100, 100)
	var target_id := registry.spawn(297, _cell(206), 100, 100)
	var hero := registry.get_actor(hero_id)
	var npc := registry.get_actor(target_id)
	var queued := talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	expect(queued["outcome"] == "approach" and not queued["move"], "input event remotely opened or started unadmitted movement")
	expect(talk.tick(registry, "idle", true)["outcome"] == "open", "exact initial distance180 should admit on simulation tick")
	npc.cell = _cell(207)
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	var far := talk.tick(registry, "idle", true)
	expect(far["outcome"] == "approach" and far["stop_radius_raw"] == 120, "distance181 must approach with native radius120")
	var saved: Dictionary = JSON.parse_string(JSON.stringify(talk.snapshot()))
	var restored := Talk.new(weapons)
	restored.bind_definition(1729, definitions[1729])
	restored.bind_definition(1200, definitions[1200])
	expect(restored.restore(saved, registry.ids()) == "", "pending command JSON restore failed")
	npc.cell = _cell(146)
	expect(restored.tick(registry, "moving", true)["outcome"] == "approach", "exact distance120 must continue active approach")
	npc.cell = _cell(145)
	expect(restored.tick(registry, "moving", true)["outcome"] == "open", "distance119 should complete approach")
	npc.cell = _cell(207)
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	talk.tick(registry, "moving", true)
	npc.cell = _cell(146)
	expect(talk.tick(registry, "idle", true)["outcome"] == "approach", "idle movement was mistaken for successful completion")
	expect(talk.tick(registry, "arrived", true)["outcome"] == "open", "native successful completion at radius boundary failed")
	npc.cell = _cell(183)
	talk.request(hero, npc, 8, 297, 0, 0, 0, 0)
	expect(talk.tick(registry, "idle", true)["outcome"] == "open", "unarmed pair radius105 must admit integer distance157")
	npc.cell = _cell(184)
	talk.request(hero, npc, 8, 297, 0, 0, 0, 0)
	expect(talk.tick(registry, "idle", true)["outcome"] == "approach", "odd-radius integer division admitted distance158")
	expect(talk.tick(registry, "moving", false)["outcome"] == "cancelled", "cleared NPC binding did not cancel")
	npc.cell = _cell(1000)
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	talk.tick(registry, "queued", true)
	expect(talk.tick(registry, "arrived", true)["outcome"] == "approach", "stale distant movement completion remotely opened")
	expect(talk.tick(registry, "blocked", true)["outcome"] == "cancelled", "failed path did not cancel")
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	npc.hp = 0
	expect(talk.tick(registry, "moving", true)["outcome"] == "cancelled", "dead target retained pending talk")
	npc.hp = 100
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	npc.flags = 0
	expect(talk.tick(registry, "moving", true)["outcome"] == "cancelled", "nonliving target with remaining HP retained talk")
	npc.flags = 1
	talk.request(hero, npc, 8, 297, 0, 0, 1729, 1200)
	registry.despawn(target_id)
	registry.spawn(297, _cell(26), 100, 100)
	expect(talk.tick(registry, "idle", true)["outcome"] == "cancelled", "retired target aliased a newer actor")
	var before := restored.snapshot()
	var bad := saved.duplicate(true)
	bad["target_id"] = 1.5
	expect(not restored.restore(bad, registry.ids()).is_empty() and restored.snapshot() == before, "fractional pending ID mutated state")
	expect(not restored.validate_snapshot(saved, registry.ids()).is_empty(), "missing pending actor accepted in save")
	print("talk_command_check OK native modes/radii/boundaries, queued approach and persistent target")
	finish()

func _cell(raw_x: int) -> Vector2:
	# Authored directly in native raw space, independently of Talk conversion.
	# The port's continuous actor position already contains its cell centre.
	# Quarter-unit interior avoids float32 straddling an integer raw boundary.
	return Vector2((float(raw_x) + 0.25) / 53.66563, 0.0)
